### PR TITLE
David Delgado

### PR DESCRIPTION
**Pull request by ddelgad5**
I added my name and strengths to the README.md file.

### CODE REVIEW

**Comment by coopervk** [comment]
If o's and -'s aren't aligning identically, then you likely aren't using a monospace font. If you look at your commit on Github, you'll see that -'s worked perfectly fine...Do you still want to use o's, then?

**Comment by ddelgad5** [comment]
@coopervk , I am referencing what it looks like off of Github so it is their font.  On Atom, it looks fine to me, but if I look at the README.md preview on Github, it uses a non monospace font.

**Comment by coopervk** [comment]
image

**Comment by ddelgad5** [comment]
md-preview

I am talking about the preview of the .md file.  Not the code changes.  Sorry for the confusion.

**Comment by coopervk** [comment]
Oh, well all right then. As much as I don't love the look of o's, I don't think it's really worth our time experimenting with characters until we find something aesthetically pleasing for something as simple as this, so I'm merging.

**Pull request merged**
